### ISSUE TITLE
Will there be a DLL for windows?

### ISSUE THREAD

**Issue by kalucky0** [mnottale/uwu#5]
There are only releases available for Linux. Do you plan on releasing a DLL for Windows? Or at least a build instruction?

**Comment by mnottale** [comment]
There is a released dll for windows. It's  called ulbridge-windows.so and you need to rename it to ulbrdige.so but it's actually a dll built for windows. This is due to a quirk in how C# imports native code for which I haven't figured a workaround yet.

**Comment by kalucky0** [comment]
SO files don't seem to be recognized as valid DLL files causing Unity to return `DllNotFoundException`

> DLLs and SOs are fundamentally different formats, so in short, no, you can't load a DLL on Linux or an SO on Windows.

**Comment by mnottale** [comment]
$  file ulbridge-windows.so 

ulbridge-windows.so: PE32+ executable (DLL) (GUI) x86-64, for MS Windows

**Comment by kalucky0** [comment]
Nevertheless Unity doesn't recognize it

**Comment by mnottale** [comment]
The problem might lie elsewhere like a dependency which is not found. You can try running a dependency walker tool on ulbridge.so to see if it has all it needs.
